import type { Types } from 'mongoose';

import { CANCELLABLE_ORDER_STATUSES } from './orders.constants';
import type { OrderSortableField } from './orders.constants';
import { OrderModel } from './order.model';
import type { IOrder, OrderStatus, PaymentMethod } from './order.types';

export interface CreateOrderInput {
  /** Pre-generated by the service (see OrdersService.placeOrder) so OrderItems can reference it before the Order document itself is written — see that method's doc comment for why. */
  _id: Types.ObjectId;
  orderNumber: string;
  canteenId: string | Types.ObjectId;
  studentId: string | Types.ObjectId;
  paymentMethod: PaymentMethod;
  subtotal: number;
  tax: number;
  discount: number;
  totalAmount: number;
  pickupToken: string;
  estimatedReadyTimeMinutes: number;
  notes?: string;
}

export interface SearchOrdersOptions {
  studentId?: string | Types.ObjectId;
  canteenId?: string | Types.ObjectId;
  orderNumber?: string;
  status?: OrderStatus;
  dateFrom?: Date;
  dateTo?: Date;
  page: number;
  limit: number;
  sortBy: OrderSortableField;
  sortOrder: 'asc' | 'desc';
}

export interface SearchOrdersResult {
  orders: IOrder[];
  total: number;
}

/**
 * Map from the target status to the Order document's timestamp field
 * that gets stamped when it's reached — kept here (not in the
 * service) since it's a data-layer concern: which field to $set.
 */
const STATUS_TIMESTAMP_FIELD: Record<string, string> = {
  accepted: 'acceptedAt',
  preparing: 'preparingAt',
  ready: 'readyAt',
  completed: 'completedAt',
};

/**
 * All Mongoose queries for the `orders` collection live here — per
 * ARCHITECTURE.md §3.1's layering rule, nothing outside this file
 * (including OrdersService) touches `OrderModel` directly.
 *
 * No `isDeleted` filtering anywhere — orders have no soft-delete
 * concept (see order.types.ts's doc comment on `IOrder`).
 */
export class OrdersRepository {
  create(input: CreateOrderInput): Promise<IOrder> {
    return OrderModel.create(input);
  }

  findById(id: string | Types.ObjectId): Promise<IOrder | null> {
    return OrderModel.findOne({ _id: id }).exec();
  }

  findByStudent(
    studentId: string | Types.ObjectId,
    options: Omit<SearchOrdersOptions, 'studentId'>,
  ): Promise<SearchOrdersResult> {
    return this.search({ ...options, studentId });
  }

  findByCanteen(
    canteenId: string | Types.ObjectId,
    options: Omit<SearchOrdersOptions, 'canteenId'>,
  ): Promise<SearchOrdersResult> {
    return this.search({ ...options, canteenId });
  }

  /**
   * The shared, general-purpose filtered/paginated query — `findByStudent`/
   * `findByCanteen` are thin wrappers around this that fix one filter
   * field, so the query-building logic (filter assembly, sort, skip/limit)
   * lives in exactly one place rather than being duplicated per endpoint.
   */
  async search(options: SearchOrdersOptions): Promise<SearchOrdersResult> {
    const filter: Record<string, unknown> = {};
    if (options.studentId !== undefined) filter.studentId = options.studentId;
    if (options.canteenId !== undefined) filter.canteenId = options.canteenId;
    if (options.orderNumber) filter.orderNumber = options.orderNumber;
    if (options.status) filter.status = options.status;
    if (options.dateFrom || options.dateTo) {
      const createdAt: Record<string, Date> = {};
      if (options.dateFrom) createdAt.$gte = options.dateFrom;
      if (options.dateTo) createdAt.$lte = options.dateTo;
      filter.createdAt = createdAt;
    }

    const sort: Record<string, 1 | -1> = { [options.sortBy]: options.sortOrder === 'asc' ? 1 : -1 };
    const skip = (options.page - 1) * options.limit;

    const [orders, total] = await Promise.all([
      OrderModel.find(filter).sort(sort).skip(skip).limit(options.limit).exec(),
      OrderModel.countDocuments(filter).exec(),
    ]);

    return { orders, total };
  }

  /**
   * Atomic: the filter itself requires the order to currently be in
   * `fromStatus` — a concurrent second request racing to advance the
   * same order gets `null` back (its expected-current-status no
   * longer matches) instead of silently double-applying a transition.
   * Same pattern as CanteensRepository.toggleOpenStatus /
   * MenuItemsRepository.updateAvailability.
   */
  updateStatus(
    id: string | Types.ObjectId,
    fromStatus: OrderStatus,
    toStatus: OrderStatus,
  ): Promise<IOrder | null> {
    const timestampField = STATUS_TIMESTAMP_FIELD[toStatus];
    return OrderModel.findOneAndUpdate(
      { _id: id, status: fromStatus },
      { $set: { status: toStatus, [timestampField]: new Date() } },
      { returnDocument: 'after' },
    ).exec();
  }

  /** Atomic: the filter requires the order to currently be in a cancellable status — see orders.constants.ts's CANCELLABLE_ORDER_STATUSES. */
  cancelOrder(id: string | Types.ObjectId, cancellationReason: string): Promise<IOrder | null> {
    return OrderModel.findOneAndUpdate(
      { _id: id, status: { $in: CANCELLABLE_ORDER_STATUSES } },
      { $set: { status: 'cancelled', cancelledAt: new Date(), cancellationReason } },
      { returnDocument: 'after' },
    ).exec();
  }
}
