import type { Types } from 'mongoose';

import { CANCELLABLE_ORDER_STATUSES } from './orders.constants';
import type { OrderSortableField } from './orders.constants';
import { OrderModel } from './order.model';
import type { IOrder, OrderStatus, PaymentMethod, PaymentStatus } from './order.types';
import { ORDER_STATUSES } from './order.types';

export interface CreateOrderInput {
  /** Pre-generated by the service (see OrdersService.placeOrder) so OrderItems can reference it before the Order document itself is written — see that method's doc comment for why. */
  _id: Types.ObjectId;
  orderNumber: string;
  canteenId: string | Types.ObjectId;
  studentId: string | Types.ObjectId;
  paymentMethod: PaymentMethod;
  subtotal: number;
  tax: number;
  discount: number;
  totalAmount: number;
  pickupToken: string;
  estimatedReadyTimeMinutes: number;
  notes?: string;
}

export interface SearchOrdersOptions {
  studentId?: string | Types.ObjectId;
  canteenId?: string | Types.ObjectId;
  orderNumber?: string;
  /** Added for the Kitchen Workflow phase's dashboard filter — see OrdersService.searchOrders. Exact match; pickupToken is a plain, non-hashed 6-digit code (see order.types.ts), so no lookup helper beyond a straight equality filter is needed. */
  pickupToken?: string;
  status?: OrderStatus;
  /** Added for the Operations Center phase (`modules/admin` frontend's `GET /kitchen/orders` filters) — see kitchen.validation.ts's doc comment on why this lives here rather than as a client-side post-filter. */
  paymentStatus?: PaymentStatus;
  /** Added for the Payments Management phase, same shape and reasoning as `paymentStatus` above. */
  paymentMethod?: PaymentMethod;
  dateFrom?: Date;
  dateTo?: Date;
  /** Inclusive bounds on `totalAmount`, paise. Added for the Operations Center phase alongside `paymentStatus` above. */
  minAmount?: number;
  maxAmount?: number;
  page: number;
  limit: number;
  sortBy: OrderSortableField;
  sortOrder: 'asc' | 'desc';
}

export interface SearchOrdersResult {
  orders: IOrder[];
  total: number;
}

/**
 * Analytics-phase read models — see ARCHITECTURE.md §3.1's
 * `modules/analytics` note. `from`/`to` are both optional so
 * `getRevenueSummary` can serve the Dashboard's unbounded "Total
 * Revenue"; every other aggregation method below requires a concrete
 * range (`AnalyticsService` always resolves one before calling them).
 */
export interface DateRangeFilter {
  from?: Date;
  to?: Date;
}

export interface RevenueSummary {
  revenue: number;
  orderCount: number;
}

export type RevenueGranularity = 'day' | 'week' | 'month' | 'year';

export interface RevenueBucket {
  periodStart: Date;
  revenue: number;
  orderCount: number;
}

export interface DayOrderCount {
  date: Date;
  count: number;
}

export interface MonthOrderCount {
  month: Date;
  count: number;
}

export interface HourOrderCount {
  hour: number;
  count: number;
}

export interface CanteenRevenue {
  canteenId: Types.ObjectId;
  revenue: number;
  orderCount: number;
}

export interface CustomerOrderStats {
  studentId: Types.ObjectId;
  orderCount: number;
  totalSpent: number;
}

/**
 * Map from the target status to the Order document's timestamp field
 * that gets stamped when it's reached — kept here (not in the
 * service) since it's a data-layer concern: which field to $set.
 */
const STATUS_TIMESTAMP_FIELD: Record<string, string> = {
  accepted: 'acceptedAt',
  preparing: 'preparingAt',
  ready: 'readyAt',
  completed: 'completedAt',
};

/** `{}` when both bounds are absent — an unfiltered $match stage, used only by getRevenueSummary's all-time Dashboard case. */
function matchDateRange(filter: DateRangeFilter): Record<string, unknown> {
  if (!filter.from && !filter.to) return {};
  const createdAt: Record<string, Date> = {};
  if (filter.from) createdAt.$gte = filter.from;
  if (filter.to) createdAt.$lte = filter.to;
  return { createdAt };
}

/**
 * All Mongoose queries for the `orders` collection live here — per
 * ARCHITECTURE.md §3.1's layering rule, nothing outside this file
 * (including OrdersService) touches `OrderModel` directly.
 *
 * No `isDeleted` filtering anywhere — orders have no soft-delete
 * concept (see order.types.ts's doc comment on `IOrder`).
 */
export class OrdersRepository {
  create(input: CreateOrderInput): Promise<IOrder> {
    return OrderModel.create(input);
  }

  findById(id: string | Types.ObjectId): Promise<IOrder | null> {
    return OrderModel.findOne({ _id: id }).exec();
  }

  findByStudent(
    studentId: string | Types.ObjectId,
    options: Omit<SearchOrdersOptions, 'studentId'>,
  ): Promise<SearchOrdersResult> {
    return this.search({ ...options, studentId });
  }

  findByCanteen(
    canteenId: string | Types.ObjectId,
    options: Omit<SearchOrdersOptions, 'canteenId'>,
  ): Promise<SearchOrdersResult> {
    return this.search({ ...options, canteenId });
  }

  /**
   * The shared, general-purpose filtered/paginated query — `findByStudent`/
   * `findByCanteen` are thin wrappers around this that fix one filter
   * field, so the query-building logic (filter assembly, sort, skip/limit)
   * lives in exactly one place rather than being duplicated per endpoint.
   */
  async search(options: SearchOrdersOptions): Promise<SearchOrdersResult> {
    const filter: Record<string, unknown> = {};
    if (options.studentId !== undefined) filter.studentId = options.studentId;
    if (options.canteenId !== undefined) filter.canteenId = options.canteenId;
    if (options.orderNumber) filter.orderNumber = options.orderNumber;
    if (options.pickupToken) filter.pickupToken = options.pickupToken;
    if (options.status) filter.status = options.status;
    if (options.paymentStatus) filter.paymentStatus = options.paymentStatus;
    if (options.paymentMethod) filter.paymentMethod = options.paymentMethod;
    if (options.dateFrom || options.dateTo) {
      const createdAt: Record<string, Date> = {};
      if (options.dateFrom) createdAt.$gte = options.dateFrom;
      if (options.dateTo) createdAt.$lte = options.dateTo;
      filter.createdAt = createdAt;
    }
    if (options.minAmount !== undefined || options.maxAmount !== undefined) {
      const totalAmount: Record<string, number> = {};
      if (options.minAmount !== undefined) totalAmount.$gte = options.minAmount;
      if (options.maxAmount !== undefined) totalAmount.$lte = options.maxAmount;
      filter.totalAmount = totalAmount;
    }

    const sort: Record<string, 1 | -1> = { [options.sortBy]: options.sortOrder === 'asc' ? 1 : -1 };
    const skip = (options.page - 1) * options.limit;

    const [orders, total] = await Promise.all([
      OrderModel.find(filter).sort(sort).skip(skip).limit(options.limit).exec(),
      OrderModel.countDocuments(filter).exec(),
    ]);

    return { orders, total };
  }

  /**
   * Atomic: the filter itself requires the order to currently be in
   * `fromStatus` — a concurrent second request racing to advance the
   * same order gets `null` back (its expected-current-status no
   * longer matches) instead of silently double-applying a transition.
   * Same pattern as CanteensRepository.toggleOpenStatus /
   * MenuItemsRepository.updateAvailability.
   */
  updateStatus(
    id: string | Types.ObjectId,
    fromStatus: OrderStatus,
    toStatus: OrderStatus,
  ): Promise<IOrder | null> {
    const timestampField = STATUS_TIMESTAMP_FIELD[toStatus];
    return OrderModel.findOneAndUpdate(
      { _id: id, status: fromStatus },
      { $set: { status: toStatus, [timestampField]: new Date() } },
      { returnDocument: 'after' },
    ).exec();
  }

  /** Atomic: the filter requires the order to currently be in a cancellable status — see orders.constants.ts's CANCELLABLE_ORDER_STATUSES. */
  cancelOrder(id: string | Types.ObjectId, cancellationReason: string): Promise<IOrder | null> {
    return OrderModel.findOneAndUpdate(
      { _id: id, status: { $in: CANCELLABLE_ORDER_STATUSES } },
      { $set: { status: 'cancelled', cancelledAt: new Date(), cancellationReason } },
      { returnDocument: 'after' },
    ).exec();
  }

  /**
   * Added for the Payments phase (see ARCHITECTURE.md §3.1's
   * `modules/payments` note) — deliberately a plain, unconditional
   * `$set`, unlike `updateStatus`'s `fromStatus` guard. Correctness
   * here is guaranteed by the caller (`PaymentsService`), whose own
   * `Payment.status` forward-transition guard already ensures this is
   * only ever invoked in a valid sequence (`paid` only after a
   * payment reaches `SUCCESS`, `refunded` only after that `SUCCESS`
   * payment is refunded) — the same trust relationship
   * `NotificationsService.notifyOrderEvent` already has with every
   * one of its callers.
   */
  updatePaymentStatus(
    id: string | Types.ObjectId,
    paymentStatus: PaymentStatus,
  ): Promise<IOrder | null> {
    return OrderModel.findOneAndUpdate(
      { _id: id },
      { $set: { paymentStatus } },
      { returnDocument: 'after' },
    ).exec();
  }

  // ---------------------------------------------------------------
  // Analytics phase — read-only aggregations. Added for
  // `modules/analytics` (see ARCHITECTURE.md §3.1's note); every
  // method below is a pure read with no side effects, consistent with
  // "read-only" being this phase's hard constraint.
  // ---------------------------------------------------------------

  /**
   * Every status, zero-filled even when a status has no orders. Called
   * two ways: unfiltered (`{}`) for the Dashboard's all-time
   * status breakdown — sum of the values is "Total Orders" — and
   * range-scoped for Order Analytics' "Orders by Status", which also
   * derives its completion rate from this same breakdown
   * (`completed / total`) rather than a second, overlapping query.
   */
  async getStatusCounts(filter: DateRangeFilter = {}): Promise<Record<OrderStatus, number>> {
    const rows = await OrderModel.aggregate<{ _id: OrderStatus; count: number }>([
      { $match: matchDateRange(filter) },
      { $group: { _id: '$status', count: { $sum: 1 } } },
    ]);
    const counts = Object.fromEntries(ORDER_STATUSES.map((status) => [status, 0])) as Record<
      OrderStatus,
      number
    >;
    for (const row of rows) counts[row._id] = row.count;
    return counts;
  }

  /**
   * Paid orders only — "revenue" means money actually collected, not
   * merely ordered. Bucketed by `createdAt` since `Order` has no
   * separate "paid at" timestamp (see ARCHITECTURE.md's
   * `modules/analytics` note on this tradeoff). `filter` with neither
   * bound is an all-time sum — the Dashboard's "Total Revenue".
   */
  async getRevenueSummary(filter: DateRangeFilter): Promise<RevenueSummary> {
    const rows = await OrderModel.aggregate<{ revenue: number; orderCount: number }>([
      { $match: { paymentStatus: 'paid', ...matchDateRange(filter) } },
      { $group: { _id: null, revenue: { $sum: '$totalAmount' }, orderCount: { $sum: 1 } } },
    ]);
    return rows[0]
      ? { revenue: rows[0].revenue, orderCount: rows[0].orderCount }
      : { revenue: 0, orderCount: 0 };
  }

  /** Revenue/order-count/avg-order-value time series, bucketed via `$dateTrunc` at the requested granularity — the Revenue Analytics endpoint's core query. */
  async getRevenueTimeSeries(filter: {
    from: Date;
    to: Date;
    granularity: RevenueGranularity;
  }): Promise<RevenueBucket[]> {
    const rows = await OrderModel.aggregate<{ _id: Date; revenue: number; orderCount: number }>([
      { $match: { paymentStatus: 'paid', createdAt: { $gte: filter.from, $lte: filter.to } } },
      {
        $group: {
          _id: { $dateTrunc: { date: '$createdAt', unit: filter.granularity } },
          revenue: { $sum: '$totalAmount' },
          orderCount: { $sum: 1 },
        },
      },
      { $sort: { _id: 1 } },
    ]);
    return rows.map((row) => ({
      periodStart: row._id,
      revenue: row.revenue,
      orderCount: row.orderCount,
    }));
  }

  /** Every order (any status), grouped by calendar day — Order Analytics' "Orders by Day". */
  async getOrdersByDay(filter: { from: Date; to: Date }): Promise<DayOrderCount[]> {
    const rows = await OrderModel.aggregate<{ _id: Date; count: number }>([
      { $match: { createdAt: { $gte: filter.from, $lte: filter.to } } },
      { $group: { _id: { $dateTrunc: { date: '$createdAt', unit: 'day' } }, count: { $sum: 1 } } },
      { $sort: { _id: 1 } },
    ]);
    return rows.map((row) => ({ date: row._id, count: row.count }));
  }

  /** Every order (any status), grouped by calendar month — Order Analytics' "Orders by Month". */
  async getOrdersByMonth(filter: { from: Date; to: Date }): Promise<MonthOrderCount[]> {
    const rows = await OrderModel.aggregate<{ _id: Date; count: number }>([
      { $match: { createdAt: { $gte: filter.from, $lte: filter.to } } },
      {
        $group: { _id: { $dateTrunc: { date: '$createdAt', unit: 'month' } }, count: { $sum: 1 } },
      },
      { $sort: { _id: 1 } },
    ]);
    return rows.map((row) => ({ month: row._id, count: row.count }));
  }

  /** Order counts grouped by hour-of-day (0-23, UTC — `$hour` uses the server's default timezone; no campus timezone is configured anywhere in this project). */
  async getPeakOrderingHours(filter: { from: Date; to: Date }): Promise<HourOrderCount[]> {
    const rows = await OrderModel.aggregate<{ _id: number; count: number }>([
      { $match: { createdAt: { $gte: filter.from, $lte: filter.to } } },
      { $group: { _id: { $hour: '$createdAt' }, count: { $sum: 1 } } },
      { $sort: { _id: 1 } },
    ]);
    return rows.map((row) => ({ hour: row._id, count: row.count }));
  }

  /**
   * Average minutes between `acceptedAt` and `readyAt` — the actual
   * kitchen prep window, deliberately excluding the queueing time
   * before acceptance and the pickup-wait time after ready. Only
   * orders where both timestamps are set (i.e. reached at least
   * `ready`) contribute; `null` when none did in range.
   */
  async getAveragePreparationTimeMinutes(filter: { from: Date; to: Date }): Promise<number | null> {
    const rows = await OrderModel.aggregate<{ avgMinutes: number }>([
      {
        $match: {
          createdAt: { $gte: filter.from, $lte: filter.to },
          acceptedAt: { $ne: null },
          readyAt: { $ne: null },
        },
      },
      {
        $group: {
          _id: null,
          avgMinutes: { $avg: { $divide: [{ $subtract: ['$readyAt', '$acceptedAt'] }, 60000] } },
        },
      },
    ]);
    return rows[0]?.avgMinutes ?? null;
  }

  /** Paid orders grouped by canteen — the source for Canteen Analytics' revenue/order-count/top-performing views (all three are one sort/slice away from this same aggregation). */
  async getRevenueByCanteen(filter: { from: Date; to: Date }): Promise<CanteenRevenue[]> {
    const rows = await OrderModel.aggregate<{
      _id: Types.ObjectId;
      revenue: number;
      orderCount: number;
    }>([
      { $match: { paymentStatus: 'paid', createdAt: { $gte: filter.from, $lte: filter.to } } },
      { $group: { _id: '$canteenId', revenue: { $sum: '$totalAmount' }, orderCount: { $sum: 1 } } },
      { $sort: { revenue: -1 } },
    ]);
    return rows.map((row) => ({
      canteenId: row._id,
      revenue: row.revenue,
      orderCount: row.orderCount,
    }));
  }

  /**
   * Per-student order activity in range — `orderCount` counts every
   * order regardless of payment outcome (a fair "how active is this
   * student" signal), while `totalSpent` sums only `paid` orders'
   * `totalAmount` (a fair "how much revenue did this student
   * generate" signal). One aggregation serves User Analytics' Active
   * Users / Repeat Customers / Top Customers — see AnalyticsService.
   */
  async getCustomerOrderStats(filter: { from: Date; to: Date }): Promise<CustomerOrderStats[]> {
    const rows = await OrderModel.aggregate<{
      _id: Types.ObjectId;
      orderCount: number;
      totalSpent: number;
    }>([
      { $match: { createdAt: { $gte: filter.from, $lte: filter.to } } },
      {
        $group: {
          _id: '$studentId',
          orderCount: { $sum: 1 },
          totalSpent: { $sum: { $cond: [{ $eq: ['$paymentStatus', 'paid'] }, '$totalAmount', 0] } },
        },
      },
    ]);
    return rows.map((row) => ({
      studentId: row._id,
      orderCount: row.orderCount,
      totalSpent: row.totalSpent,
    }));
  }
}
